### ISSUE TITLE
PhantomJS detected, but wrong version

### ISSUE THREAD

**Issue by hachel** [samcreate/Apollo-Player#14]
Hi there,
I don't know how active this project still is, but I've been trying to install it on my rasp2 running archlinux arm.
When I first ran npm install it quit with saying that there was no phantomjs binary for my system and I should install it globally which I did via pacman.
Now it complains it is not the correct version. My version is 2.0.0 and somehow it needs 1.9.19 and won't continue without it:

``` javascript
> phantomjs@1.9.19 install /home/alarm/.config/mopidy/httpfrontends/Apollo-Player/node_modules/phantomjs
> node install.js

Found PhantomJS at /usr/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 2.0.0 @ /usr/bin/phantomjs.
Unexpected platform or architecture: linux/arm
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm WARN Apollo@1.0.0 No repository field.
npm WARN Apollo@1.0.0 No license field.
npm ERR! Linux 4.1.15-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
...
```

I haven't found any reference to version 1.9.19 anywhere so I don't know how to manually fix it.
Any help would be appreciated!
thanks

**Comment by samcreate** [comment]
I haven't had the time to invest in keeping this up-to-date. Any issues are
going to have to be slogged through. Sorry about that!

**Comment by hachel** [comment]
I've able to get it to work by forcing (-f flag) the node.js install command and installing phantomjs via the system's packet manager.
